django/17-02/product/urls.py
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.urls import path

from .views import view1, view2, View3, increase_sotck, decrease_stock

app_name = "product"

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html")),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("view1/", view1, name="view1"),
    path("view2/", view2, name="view2"),
    path("view3/", View3.as_view(), name="view3"),
    path("increase_stock/", increase_sotck, name="increase_stock"),
    path("decrease_stock/", decrease_stock, name="decrease_stock"),
]

django/17-02/product/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    on_sale = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField("Tag", blank=True)

    class Meta:
        verbose_name = "상품"
        verbose_name_plural = "상품"
        ordering = ("name",)

    def __str__(self):
        return self.name


class ProductOption(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.CharField(max_length=50, blank=True, null=True)
    size = models.CharField(max_length=50, blank=True, null=True)
    stock = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name = "상품 옵션"
        verbose_name_plural = "상품 옵션"
        unique_together = ("product", "color", "size")
        permissions = [
            ("can_update_stock", "재고 관리 권한"),
        ]

    def __str__(self):
        return f"{self.product.name} - {self.color} - {self.size}"


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = "태그"
        verbose_name_plural = "태그"
        ordering = ("name",)

    def __str__(self):
        return self.name

django/17-02/product/views.py
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.contrib.auth.decorators import permission_required
from .models import ProductOption


def login_view(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponse("로그인 성공")
    else:
        return HttpResponse("로그인 실패")
    

def logout_view(request):
    logout(request)
    return HttpResponse("로그아웃 성공")


def view1(request):
    if request.user.is_authenticated:
        return HttpResponse("로그인 되어 있습니다.")
    else:
        return HttpResponse("로그인 되어 있지 않습니다.")


@login_required
def view2(request):
    return HttpResponse("로그인 되어 있습니다.")


class View3(LoginRequiredMixin, View):
    def get(self, request):
        return HttpResponse("로그인 되어 있습니다.")


def increase_sotck(request):
    if not request.user.has_perm("product.can_update_stock"):
        raise PermissionError("재고를 업데이트할 권한이 없습니다.")
    option = ProductOption.objects.get(pk=1)
    option.stock += 1
    option.save()
    return HttpResponse(f"재고를 추가 했습니다. 현재 재고: {option.stock}개")


# raise_exception=True로 설정하면, 권한이 없을 때 PermissionDenied 예외가 발생합니다.
# raise_exception=False로 설정하면 권한이 없을 때 로그인 페이지로 리다이렉트 됩니다.
@permission_required("product.can_update_stock", raise_exception=True)
def decrease_stock(request):
    option = ProductOption.objects.get(pk=1)
    option.stock -= 1
    if option.stock < 0:
        raise ValueError("재고가 부족합니다.")
    option.save()
    return HttpResponse(f"재고를 차감 했습니다. 현재 재고: {option.stock}개")

django/17-02/product/templates/_base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{{ title }}{% endblock %}</title>
</head>
<body>
{% block contents %}{% endblock %}
</body>
</html>

django/17-02/product/templates/index.html
{% extends "_base.html" %}

{% block title %}링크{% endblock %}

{% block contents %}
<h1>링크</h1>
<p>
  <a href="{% url 'admin:index' %}">Admin Page</a>
</p>
{% if user.is_authenticated %}
<p>안녕하세요, {{ user.username }}님</p>
<form method="post" action="{% url 'product:logout' %}">
{% csrf_token %}
<button type="submit">로그아웃</button>
</form>
{% else %}
<a href="{% url 'product:login' %}">로그인</a>
{% endif %}

{# view1 ~ view 3 #}
<h3>로그인 확인 뷰</h3>
<ul>
  <li><a href="{% url 'product:view1' %}" target="_blank">view1</a></li>
  <li><a href="{% url 'product:view2' %}" target="_blank">view2</a></li>
  <li><a href="{% url 'product:view3' %}" target="_blank">view3</a></li>
</ul>

{# 재고 수정 권한이 있는지 메시지 표시 #}
<h3>권한 확인 뷰</h3>
{% if perms.product.can_update_stock %}
<p>재고 수정 권한이 있습니다.</p>
{% else %}
<p>재고 수정 권한이 없습니다.</p>
{% endif %}
<a href="{% url 'product:increase_stock' %}" target="_blank">재고 추가</a>
<a href="{% url 'product:decrease_stock' %}" target="_blank">재고 차감</a>
{% endblock %}

django/17-02/product/templates/login.html
{% extends "_base.html" %}

{% block title %}로그인{% endblock %}

{% block contents %}
<form method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="로그인">
</form>
{% endblock %}