django/16-05/blog/urls.py
from django.urls import path

from .views import post_list, post_create, post_edit

app_name = 'blog'

urlpatterns = [
    path('posts', post_list, name='post_list'),
    path('posts/create/', post_create, name='post_create'),
    path('posts/<int:pk>/', post_edit, name='post_edit'),
]

django/16-05/blog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(
        Category, 
        on_delete=models.CASCADE, 
        related_name='posts',
        null=True,
    )

    def __str__(self):
        return self.title

django/16-05/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

    def clean_title(self):
        title = self.cleaned_data['title']
        if '[임시]' in title:
            raise ValidationError('제목에 [임시]를 포함할 수 없습니다.')
        return title
    
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')
        if title and content:
            if title == content:
                raise ValidationError('제목과 내용이 같습니다.')
        return cleaned_data

django/16-05/blog/views.py
from django.shortcuts import render, redirect

from .forms import PostForm
from .models import Post


def post_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect("blog:post_list")
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form})


def post_edit(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect("blog:post_list")
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {'form': form})

django/16-05/blog/templates/blog/post_form.html
<!DOCTYPE html>
<html>
<head>
  <title>포스트 등록 &sol; 수정</title>
</head>
<body>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">저장</button>
  </form>
</body>
</html>

django/16-05/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html>
<head>
  <title>포스트 등록</title>
</head>
<body>
  <a href="{% url 'blog:post_create' %}">새 포스트 등록</a>
  {% for post in posts %}
    <div class="post">
      <hr>
      <a href="{% url 'blog:post_edit' post.pk %}">{{ post.pk }}번 포스트 편집</a>
      <h2>{{ post.title }}</h2>
      <p>{{ post.content }}</p>
    </div>
  {% empty %}
    <p>등록한 포스트가 없습니다.</p>
  {% endfor %}
</body>
</html>