django/16-09/music/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'music'

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path('artists/', views.artist_list, name="artist_list"),
    path('artists/<int:id>/', views.artist_detail, name="artist_detail"),
    path('albums/', views.albums_list, name="album_list"),
    path('albums/<int:id>/', views.albums_detail, name="album_detail"),
    path('statistics/', views.statistics_view, name="statistics"),
]

django/16-09/music/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.urls import reverse

class Artist(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='artists/') 
    description = models.TextField()

    def __str__(self):
        return self.name

class Album(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    image = models.ImageField(upload_to='albums/') 
    artist = models.ForeignKey(
        Artist, 
        on_delete=models.CASCADE,
        related_name='albums',
    )
    release_date = models.DateField()
    genre = models.CharField(max_length=50)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("music:album_detail", kwargs={"id": self.pk})
    
    @property
    def url(self):
        return self.get_absolute_url()


class Song(models.Model):
    album = models.ForeignKey(
        Album, 
        on_delete=models.CASCADE, 
        related_name='songs',
    )
    title = models.CharField(max_length=255)
    duration = models.DurationField(default=0)

    def __str__(self):
        return self.title

django/16-09/music/views.py
from django.shortcuts import render
from django.db.models import Count, Sum, Min, Max, Avg, StdDev, Variance

from music.models import Artist, Album, Song
from django.shortcuts import get_object_or_404

def artist_list(request):
    artists = Artist.objects.all()
    return render(request, 'artist-list.html', {'artists': artists})

def artist_detail(request, id):
    artist = get_object_or_404(Artist, id=id)
    return render(request, 'artist-detail.html', {'artist': artist})

def albums_list(request):
    albums = Album.objects.annotate(
        song_count=Count('songs'),  # 곡 수
        average_song_duration=Avg('songs__duration'),   # 평균 곡 길이
        longest_song_duration=Max('songs__duration'),   # 가장 긴 곡 길이
        total_duration=Sum('songs__duration')        # 총 곡 길이
    )
    return render(request, 'album-list.html', {'albums': albums})

def albums_detail(request, id):
    album = get_object_or_404(Album, id=id)
    return render(request, 'album-detail.html', {'album': album})

def statistics_view(request):
    statistics = Album.objects.aggregate(
        album_count=Count('id'),  # 앨범 수
        earliest_release=Min('release_date'),  # 가장 이른 발매일
        latest_release=Max('release_date'),  # 가장 늦은 발매일
        total_songs=Sum('songs__id'),  # 총 곡 수
        average_duration=Avg('songs__duration'),  # 평균 곡 길이
        duration_stddev=StdDev('songs__duration'),  # 곡 길이의 표준 편차
        duration_variance=Variance('songs__duration')  # 곡 길이의 분산
    )
    return render(request, 'statistics.html', {'statistics': statistics})

django/16-09/music/templates/_page_base.html
{% spaceless %}
{% load static i18n captureas %}
{% get_current_language as LANGUAGE_CODE %}
{% captureas page_site_name %}{% block site_name %}{% trans '사이트 이름' %}{% endblock %}{% endcaptureas %}
{% captureas page_title %}{% block title %}{% trans '페이지 이름' %}{% endblock %}{% endcaptureas %}
{% captureas page_subtitle %}{% block subtitle %}{% endblock %}{% endcaptureas %}
{% captureas page_description %}{% block description %}{% trans '페이지 설명' %}{% endblock %}{% endcaptureas %}
{% captureas page_og_image %}{% block og_image %}{% static 'icon/logo-og.png' %}{% endblock %}{% endcaptureas %}
{% captureas page_canonical_link %}{% block canonical_link %}{% endblock %}{% endcaptureas %}
{% endspaceless %}{% block html %}{% spaceless %}
<!doctype html>
<html {% block html_tag_attributes %}lang="{{ LANGUAGE_CODE }}"{% endblock %}>
<head>
  {% block meta %}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="description" content="{{ page_description }}">
  <meta property="og:site_name" content="{{ page_site_name }}">
  <meta property="og:title" content="{{ page_title }}{% if page_subtitle %} - {{ page_subtitle }}{% endif %}">
  <meta property="og:description" content="{{ page_description }}">
  <meta property="og:url" content="{% if page_canonical_link %}{{ page_canonical_link }}{% else %}{{ request.build_absolute_uri }}{% endif %}">
  <meta property="og:type" content="website">
  <meta property="og:image" content="{{ page_og_image }}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{{ page_title }}{% if page_subtitle %} - {{ page_subtitle }}{% endif %}">
  <meta name="twitter:description" content="{{ page_description }}">
  <meta name="twitter:image" content="{{ page_og_image }}">
  {% endblock %}

  {% block link %}
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="icon" sizes="192x192" href="{% static 'icon/logo-192x192.png' %}">
  <link rel="apple-touch-icon" href="{% static 'icon/logo-180x180.png' %}">
  <link rel="mask-icon" href="{% static 'icon/safari-pinned-tab.svg' %}" color="#ffffff">
  <link rel="manifest" href="{% static 'manifest.json' %}">
  {% endblock %}

  {% if page_canonical_link %}<link rel="canonical" href="{{ page_canonical_link }}">{% endif %}
  <title>{{ page_title }}{% if page_subtitle %} - {{ page_subtitle }}{% else %} - {{ site_name }}{% endif %}</title>

  {% block extrastyle %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
  {% endblock %}
</head>
{% endspaceless %}
<body>
  {% include '_page_navbar.html' %}

  {% block content %}{% endblock %}

  {% include '_page_footer.html' %}
</body>
{% spaceless %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
{% endblock %}
{% endspaceless %}
</html>
{% endblock %}

django/16-09/music/templates/_page_footer.html
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>
</div>

django/16-09/music/templates/_page_navbar.html
<div class="container">
  <header
    class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom"
  >
    <a
      href="{% url 'music:index' %}"
      class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
    >
      <svg class="bi me-2" width="40" height="32">
        <use xlink:href="#bootstrap"></use>
      </svg>
      <span class="fs-4">{{ page_site_name }}</span>
    </a>

    <ul class="nav nav-pills">
      {% url 'music:artist_list' as menu_url %}
      <li class="nav-item">
        <a
          href="{{ menu_url}}"
          class="nav-link{% if menu_url in request.path %} active{% endif %}"
          aria-current="page"
          >아티스트</a
        >
      </li>
      {% url 'music:album_list' as menu_url %}
      <li class="nav-item">
        <a
          href="{{ menu_url}}"
          class="nav-link{% if menu_url in request.path %} active{% endif %}"
          aria-current="page"
          >앨범</a
        >
      </li>
      {% url 'music:statistics' as menu_url %}
      <li class="nav-item">
        <a
          href="{{ menu_url}}"
          class="nav-link{% if menu_url in request.path %} active{% endif %}"
          aria-current="page"
          >통계</a
        >
      </li>
    </ul>
  </header>
</div>

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path
      fill-rule="evenodd"
      clip-rule="evenodd"
      d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
    ></path>
  </symbol>
  <symbol id="home" viewBox="0 0 16 16">
    <path
      d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"
    ></path>
  </symbol>
  <symbol id="speedometer2" viewBox="0 0 16 16">
    <path
      d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"
    ></path>
    <path
      fill-rule="evenodd"
      d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"
    ></path>
  </symbol>
  <symbol id="table" viewBox="0 0 16 16">
    <path
      d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"
    ></path>
  </symbol>
  <symbol id="people-circle" viewBox="0 0 16 16">
    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
    <path
      fill-rule="evenodd"
      d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"
    ></path>
  </symbol>
  <symbol id="grid" viewBox="0 0 16 16">
    <path
      d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"
    ></path>
  </symbol>
</svg>

django/16-09/music/templates/album-detail.html
{% extends '_page_base.html' %}

{% block meta %}{{ block.super }}
{% endblock %}

{% block css %}{{ block.super }}
{% endblock %}

{% block title%}앨범: {{ album.title }}{% endblock %}

{% block content %}
<div class="container">
  <h2>{{ page_title }}</h2>
  <div class="row">
    <div class="col-md-4">
      <img src="{{ album.image }}" alt="{{ album.name }}" class="img-responsive">
    </div>
    <div class="col-md-8">
      <p>{{ album.description }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3>곡</h3>
      <ul>
        {% for song in album.songs.all %}
        <li>{{ song.title }}</a> {{ song.duration }}</li>
        {% endfor %}
      </ul>
    </div>
</div>
{% endblock %}

django/16-09/music/templates/album-list.html
{% extends '_page_base.html' %}

{% block meta %}{{ block.super }}
{% endblock %}

{% block css %}{{ block.super }}
{% endblock %}

{% block title%}앨범 목록{% endblock %}

{% block description%}앨범 목록 페이지입니디{% endblock %}

{% block content %}
  <div class="container">  
    <h3>{{ page_title }}</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">앨범 이름</th>
          <th scope="col">곡 수</th>
          <th scope="col">전체 시간</th>
        </tr>
      </thead>
      <tbody>
        {% for album in albums %}
        <tr>
          <th scope="row">{{ album.id }}</th>
          <td><a href="{% url 'music:album_detail' album.id %}">{{ album.title }}</a></td>
          <td>{{ album.song_count }}</td>
          <td>{{ album.total_duration }}</td>
        </tr>
        {% empty %}
        <tr>
          <th scope="row" colspan="3">앨범이 없습니다</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

django/16-09/music/templates/artist-detail.html
{% extends '_page_base.html' %}

{% block meta %}{{ block.super }}
{% endblock %}

{% block css %}{{ block.super }}
{% endblock %}

{% block title%}아티스트: {{ artist.name }}{% endblock %}

{% block content %}
<div class="container">
  <h3>{{ page_title }}</h3>
  <div class="row">
    <div class="col-md-4">
      <img src="{{ artist.image.url }}" alt="{{ artist.name }}" class="img-responsive">
    </div>
    <div class="col-md-8">
      <p>{{ artist.description }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3>앨범</h3>
      <ul>
        {% for album in artist.albums.all %}
        <li><a href="{{ album.url }}">{{ album.title }}</a> {{ album.genre }} / {{ album.release_date }}</li>
        {% endfor %}
      </ul>
    </div>
</div>
{% endblock %}

django/16-09/music/templates/artist-list.html
{% extends '_page_base.html' %}

{% block meta %}{{ block.super }}
{% endblock %}

{% block css %}{{ block.super }}
{% endblock %}

{% block title%}아티스트 목록{% endblock %}

{% block content %}
<div class="container">
  <h3>{{ page_title }}</h3>
  <ul>
    {% for artist in artists %}
    <li><a href="{% url 'music:artist_detail' artist.id %}">{{ artist.name }}</a></li>
    {% empty %}
    <li>앨범이 없습니다.</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

django/16-09/music/templates/index.html
{% extends '_page_base.html' %}

{% block meta %}{{ block.super }}
{% endblock %}

{% block css %}{{ block.super }}
{% endblock %}

{% block title%}링크{% endblock %}

{% block content %}
<div class="container">
  <h3>{{ page_title }}</h3>
  <a href="{% url 'music:artist_list' %}">아티스트</a><br/>
  <a href="{% url 'music:album_list' %}">앨범</a><br/>
  <a href="{% url 'music:statistics' %}">통계</a><br/>
</div>
{% endblock %}

django/16-09/music/templates/statistics.html
{% extends '_page_base.html' %}

{% block meta %}{{ block.super }}
{% endblock %}

{% block css %}{{ block.super }}
{% endblock %}

{% block title %}통계{% endblock %}

{% block content %}
  <div class="container">  
    <h3>{{ page_title }}</h3>
    <ul>
      {% for key, value in statistics.items %}
      <li>
        {{ key }} : {{ value }}
      </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}